-- Issue #4758: [PL/SQL] Exponential parse time on sum(column) + sum(column) + sum(column) + ...
-- URL: https://github.com/antlr/grammars-v4/issues/4758

SELECT
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) +
    SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME) + SUM(COLUMN_NAME)
FROM TABLE_NAME;
