-- Issue #3822: PL/SQL improper use of TIMEZONE token
-- URL: https://github.com/antlr/grammars-v4/issues/3822

SELECT 0 AS ID, 'AMERICA/DENVER' AS TIMEZONE FROM DUAL UNION ALL
SELECT 1 AS ID, 'ETC/GMT+12' AS TIMEZONE FROM DUAL UNION ALL
SELECT 2 AS ID, 'ETC/GMT+11' AS TIMEZONE FROM DUAL;
