-- Issue #1048: Select list elements does not work if the first element is dot notated aliased entity
-- URL: https://github.com/antlr/grammars-v4/issues/1048

SELECT PTR.PBLCTN_TRNSCTN_RUN_ID,PTX.PBLCTN_TRNSCTN_NM, PTR.SRC_ID FROM TEST_OWNER.TEST_PBLCTN_TRNSCTN PT
JOIN TEST_OWNER.TEST_PBLCTN_TRNSCTN_RUN@BIGBOX PTR
ON TTR.PBLCTN_TRNSCTN_ID = TT.PBLCTN_TRNSCTN_ID;

SELECT NULL, PTR.PBLCTN_TRNSCTN_RUN_ID,PTX.PBLCTN_TRNSCTN_NM, PTR.SRC_ID FROM TEST_OWNER.TEST_PBLCTN_TRNSCTN PT
JOIN TEST_OWNER.TEST_PBLCTN_TRNSCTN_RUN@BIGBOX PTR
ON TTR.PBLCTN_TRNSCTN_ID = TT.PBLCTN_TRNSCTN_ID;