-- Issue #3043: sql/plsql not parsing apparently valid query string
-- URL: https://github.com/antlr/grammars-v4/issues/3043

CREATE TABLE "X"."Y" ( "OID" NUMBER(19,0) NOT NULL ENABLE, "STANDARDIZED_HOME_PHONE" GENERATED ALWAYS AS (115) VIRTUAL , ) ;
CREATE TABLE "A"."B" ( "FIELD1" NUMBER(19,0) NOT NULL ENABLE, "FIELD2" NUMBER(19,0) NOT NULL ENABLE, PRIMARY KEY ("FIELD1") ENABLE ) ORGANIZATION INDEX NOCOMPRESS ;